# Title         : doxygen.yml
# Description   : Configura GitHub Actions para realizar la documentación en formato Doxygen
# Author        : Veltys
# Date          : 2022-12-27
# Version       : 1.2.2
# Usage         : (usado externamente)
# Notes         : 


name: Doxygen Action

on: 
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      
      - name: "Doxygen Action"
        uses: mattnotmitt/doxygen-action@master

      - name: "Commit"
        run: |
          git config --local user.name "github-actions[bot]"
          git add docs/
          git commit -m "ADD: HTML Doxygen documentation"

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}